version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=localhost
      - DB_PASSWORD=root
      - DB_NAME=mini_project
    ports:
      - 8081:8081
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mini_project
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
